# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: base_link_group
  joint_model_group_pose: base_link_group_state
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
    - name: multi_dof_joint_trajectory_action
      #type: trajectory_msgs/MultiDofFollowJointTrajectory
      action_ns: "follow_joint_trajectory"
      type: FollowJointTrajectory
      default: true
      joints:
          - virtual_joint
